In [6]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

You spent a few days measuring trees for a forest inventory survey. You now have a moderately large dataset but now comes the tricky part: data analysis.

Read your dataset 'trees_nm.csv' into a python dataframe using the following:    
`trees = pd.read_csv('dataset_name')`

In [7]:
trees = pd.read_csv('trees_nm.csv')

Input `variable_name`

Figure out how many trees there are in the dataset? Use `len(variable_name)`

How many papaya trees did you measure? You will need to search to find the scientific name.  

`count = (trees['insert species column name'] == 'insert papaya tree scientific name').sum()`

Using the above example of how to calculate this using the code figure out how many of each of the following trees you measured? Enter your code below the comments: 

1. African tulips
2. Raintrees
3. Rhizophora spp.
4. Bruguiera spp.
5. Banana

In [8]:
#1 African tulips

In [9]:
#2 Raintrees

In [10]:
#3 Rhizophora spp.

In [11]:
#4 Bruguiera spp.

In [12]:
#5 Banana

Example of how to calculate the minimum height for all papaya trees measured within the dataset. You will need to enter the papaya tree scientific name: 

`min_height = trees.loc[trees['Tree species scientific'] == 'insert papaya tree variable', 'Height of tree (m)'].min()`  

Then use `print(min_height)` to display

Replicate this process for the max height and then the average using the `.max()` and `.mean()` functions, respectively. Enter your code below the comments:

In [13]:
#1 .max()

In [14]:
#2 .mean()

Now work out the min, max and mean dbh values for the Rhizophora spp. and Bruguiera spp.

In [15]:
#3 Rhizophora spp.

In [16]:
#4 Bruguiera spp.

#### Calculate the Above Ground Biomass (AGB) for the following trees:

##### One common form of the equation is AGB = a(ρD²H)ᵇ, where:  

AGB: is the aboveground biomass.  
ρ: is the wood density.  
D: is the diameter at breast height (DBH).  
H: is the total tree height.  

Define each parameter in this equation within a variable:

In [17]:
print(trees.columns)

Index(['Surveyor', 'GlobalID', 'Tree species scientific', 'Height of tree (m)',
       'DBH (cm)', 'Density', 'x', 'y'],
      dtype='object')

In [18]:
trees

,Surveyor,GlobalID,Tree species scientific,Height of tree (m),DBH (cm),Density,x,y
0,Nick Metherall Nasolo June 2022,088df9e6-8f99-4b95-b191-4996d70c52f8,Carica papaya,3.90,5.3,0.75,177.682220,-17.572516
1,Nick Metherall Nasolo June 2022,52e56696-fcc5-4ead-a3c4-6943d9659211,Spathodea campanulata,8.20,11.8,0.45,177.683702,-17.572183
2,Nick Metherall Nasolo June 2022,b127db32-d95b-46c4-863c-60bac9561997,Spathodea campanulata,4.00,9.5,0.45,177.683416,-17.571672
3,Nick Metherall Nasolo June 2022,c5e61007-9ca3-49fe-8af2-be6e3c45a5d7,Spathodea campanulata,16.30,50.3,0.45,177.683687,-17.572132
4,Nick Metherall Nasolo June 2022,e7065e0a-a2fa-4f3b-a11d-5debd5634e51,Spathodea campanulata,17.40,53.2,0.45,177.683680,-17.572156
...,...,...,...,...,...,...,...,...
431,Mere Nick Nailaga July 2022,a5a55208-4cc8-4dd0-96b2-f3b93b73be21,Samanea saman,9.71,32.8,0.45,177.668023,-17.507451
432,Mere Nick Nailaga July 2022,8f2bf454-a2a0-40b0-a452-4068f4ece73a,Samanea saman,5.00,12,0.00,177.667937,-17.507486
433,Mere Nick Nailaga July 2022,342d6787-5f22-417b-8d2d-d43ecf086c11,Samanea saman,7.40,36.6,0.00,177.667946,-17.507519
434,Mere Nick Nailaga July 2022,2aa02d45-6624-428b-9723-ed11351794e7,Samanea saman,7.50,15.4,0.00,177.667953,-17.507515
435,Mere Nick Nailaga July 2022,5c043361-7a90-48c1-bd51-b62a37b79354,Samanea saman,5.80,13.1,0.00,177.667965,-17.507522

#### Define the equation as another variable

In [19]:
trees['DBH (cm)'] = pd.to_numeric(trees['DBH (cm)'], errors='coerce')
trees['Density'] = pd.to_numeric(trees['Density'], errors='coerce')
trees['Height of tree (m)'] = pd.to_numeric(trees['Height of tree (m)'], errors='coerce')

# Now assign variables
p = trees['Density']
D = trees['DBH (cm)']
H = trees['Height of tree (m)']

# Now you can safely multiply
AGB = p * D * H

In [20]:
trees['AGB'] = AGB
trees

,Surveyor,GlobalID,Tree species scientific,Height of tree (m),DBH (cm),Density,x,y,AGB
0,Nick Metherall Nasolo June 2022,088df9e6-8f99-4b95-b191-4996d70c52f8,Carica papaya,3.90,5.3,0.75,177.682220,-17.572516,15.5025
1,Nick Metherall Nasolo June 2022,52e56696-fcc5-4ead-a3c4-6943d9659211,Spathodea campanulata,8.20,11.8,0.45,177.683702,-17.572183,43.5420
2,Nick Metherall Nasolo June 2022,b127db32-d95b-46c4-863c-60bac9561997,Spathodea campanulata,4.00,9.5,0.45,177.683416,-17.571672,17.1000
3,Nick Metherall Nasolo June 2022,c5e61007-9ca3-49fe-8af2-be6e3c45a5d7,Spathodea campanulata,16.30,50.3,0.45,177.683687,-17.572132,368.9505
4,Nick Metherall Nasolo June 2022,e7065e0a-a2fa-4f3b-a11d-5debd5634e51,Spathodea campanulata,17.40,53.2,0.45,177.683680,-17.572156,416.5560
...,...,...,...,...,...,...,...,...,...
431,Mere Nick Nailaga July 2022,a5a55208-4cc8-4dd0-96b2-f3b93b73be21,Samanea saman,9.71,32.8,0.45,177.668023,-17.507451,143.3196
432,Mere Nick Nailaga July 2022,8f2bf454-a2a0-40b0-a452-4068f4ece73a,Samanea saman,5.00,12.0,0.00,177.667937,-17.507486,0.0000
433,Mere Nick Nailaga July 2022,342d6787-5f22-417b-8d2d-d43ecf086c11,Samanea saman,7.40,36.6,0.00,177.667946,-17.507519,0.0000
434,Mere Nick Nailaga July 2022,2aa02d45-6624-428b-9723-ed11351794e7,Samanea saman,7.50,15.4,0.00,177.667953,-17.507515,0.0000
435,Mere Nick Nailaga July 2022,5c043361-7a90-48c1-bd51-b62a37b79354,Samanea saman,5.80,13.1,0.00,177.667965,-17.507522,0.0000